name: Ai Dev Kit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Ai_Dev_Kit:
    runs-on: ubuntu-latest
    steps:
      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
          databricks --version

      - name: Install and use Node npm
        run: |
 
            NODE_VERSION="v20.15.1"   # adjust as needed
            DISTRO="linux-x64"        # change if you're on ARM or another arch

            # Create local install directory
            mkdir -p $HOME/.local/nodejs

            # Download Node.js tarball
            curl -o node.tar.xz https://nodejs.org/dist/$NODE_VERSION/node-$NODE_VERSION-$DISTRO.tar.xz

            # Extract into local directory
            tar -xJf node.tar.xz -C $HOME/.local/nodejs --strip-components=1

            # Update PATH (add to .bashrc or .zshrc for persistence)
            echo 'export PATH=$HOME/.local/nodejs/bin:$PATH' >> $HOME/.bashrc
            export PATH=$HOME/.local/nodejs/bin:$PATH

            # Verify installation
            node -v
            npm -v


      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          source ~/.bashrc
          uv --version

      - name: Setup Databricks Profile
        run: |
           export DATABRICKS_HOST=${{ vars.DATABRICKS_HOST }}
           export DATABRICKS_CLIENT_ID=${{ vars.DATABRICKS_CLIENT_ID }}
           export DATABRICKS_CLIENT_SECRET=${{ secrets.DATABRICKS_CLIENT_SECRET }}
           databricks auth describe 

      - name: Deploy Ai Dev Kit
        run: |
           git clone https://github.com/databricks-solutions/ai-dev-kit.git
           cd ai-dev-kit/databricks-builder-app
           ./scripts/deploy.sh ai-dev-kit